[package]
name = "nvim-upgrade"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
flate2 = { version = "1.0", features = ["zlib-ng"], default-features = false }
zip-extract = "0.2.2"
tar = "0.4.44"
native-dialog = "0.8.6"
