# Configuration for goneovim
# Path:
#   GNU/Linux -> $HOME/.config/goneovim/settings.toml
#   Windows   -> $HOMEPATH/.goneovim/settings.toml

[Editor]
BorderlessWindow = false
ExtCmdline   = true
ExtPopupmenu = true
ExtTabline   = true
DisableLigatures = false
Clipboard = true
DisableImeInNormal = false
SmoothScroll = false
DisableHorizontalScroll = false
DrawBorderForFloatWindow = false
DrawShadowForFloatWindow = true
ClickEffect = false
Ginitvim = "call my#misc#vim_source('ginit')"

[Cursor]
SmoothMove = true

[Palette]
AreaRatio = 0.5
MaxNumberOfResultItems = 30
Transparent = 0.92

[Message]
Transparent = 0.92

[Tabline]
Visible = true
ShowIcon = true

[Popupmenu]
ShowDetail = true
Total = 20
MenuWidth = 400
InfoWidth = 1
DetailWidth = 250
ShowDigit = false

[ScrollBar]
Visible = false

[MiniMap]
Disable = false
Visible = true
Width = 100

[Markdown]
Disable = false
CodeHlStyle = "github"

[FileExplore]
MaxDisplayItems = 15

[Statusline]
Visible = true
Left = [ "mode", "filepath", "filename" ]
Right = [ "message", "git", "fileformat", "fileencoding", "filetype" ]

[Workspace]
PathStyle = "minimum"
RestoreSession = false
