[package]
name = "nmail"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ex-util = { git = "https://github.com/AnthonyK213/ex-util" }
imap = { git = "https://github.com/AnthonyK213/rust-imap" }
lettre = "0.10"
