[package]
name = "nmail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.10"
nvim-oxi = "0.1.3"

[dependencies.imap]
version = "2.4.1"
default-features = false
