[package]
name = "nmail"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
imap = { git = "https://github.com/AnthonyK213/rust-imap" }
lettre = "0.10"
_ffi_util = { path = "../_ffi_util" }
